# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: '3.11'

jobs:
  testing:
    uses: quatrope/scikit-criteria/.github/workflows/tests.yml@c1bde1a11bd073b6407be7448e9a8cdccfc62b1a